#' @title Volcano Plots for DE genes in Seurat
#' @description wrapper for enhancedVolcano, made specifically for DE gene tables in Seurat 4.0 (careful Seurat <4.0 has "avg_logFC"
#' column instead of "avg_log2FC")
#' @param x data.frame generated by FindMarkers(), or in the same format.
#' @param Condition name of metadata column to use for color coding, used only if do.col=TRUE
#' @param p_cutoff,FC_cutoff Position in the plot where lines should be drawn, separating significant DE genes from non significant
#' @param legend Legend position see ggplot
#' @param titles if used in loop, what titles should the single plots have? If you just look at clusters,this would be levels(x$cluster).
#' @param do.col Should a color code be included?
#' @param lab.size,title.size,axis.font.size Change the fontsizes of the single graph elements
#' @param selected_genes Genelabel you want to appear in the plot
#' @param dot.size size of dots representing each gene in plot
#' @export
Volcano_plot<-function(x,Condition,p_cutoff=1e-05,FC_cutoff=1,legend="none",titles=levels(x$cluster),do.col=F,
                       lab.size=7,title.size=12,axis.font.size=7,selected_genes=NULL,dot.size=1){
  # define custom color for conditions


 geno_col<-NULL
   if(do.col==T)
  {
    geno_col <- x[,Condition]
    names(geno_col)<-geno_col
    levels(geno_col)<-my_cols[1:length(levels(geno_col))]
  }

  plot<-do.call(EnhancedVolcano::EnhancedVolcano,args=c(list(toptable=x,
                                            lab=rownames(x),
                                            x="avg_log2FC",
                                            y="p_val_adj",
                                            labSize=lab.size,
                                            title=titles,
                                            titleLabSize=title.size,
                                            subtitle=NULL,
                                            caption=NULL,
                                            legendLabSize = 7,
                                            legendIconSize = NULL,
                                            legendLabels = ggplot2::element_blank(),
                                            legendPosition = legend,
                                            axisLabSize = axis.font.size,
                                            pCutoff = p_cutoff,
                                            FCcutoff = FC_cutoff,
                                            selectLab=selected_genes,
                                            pointSize=dot.size),
                                       list(colCustom = geno_col)[do.col]
  ))

}
